version: '3.9'

services:
  webapp:
    build: .
    ports:
      - "8070:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=d330ec6b-2ed5-4c19-aa71-a9373a8c4f91.hsvc.ir,32335;Database=DBKham;User Id=sa;Password=PaN5DDK73f4USdysMqynBt8WUB75q3jY;TrustServerCertificate=True;
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "HySLHIlckL9XFDg8THGh4JOJer73mUGG"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
