version: '3.9'

services:
  webapp:
    build: .
    ports:
      - "8070:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=6b3d91c4-9ef1-47a2-89c8-61c8a5a02554.hsvc.ir,32019;Database=sohrabi;User Id=sa;Password=LHjf12dRsWZREjag00JAd0apyFxgZZKn;TrustServerCertificate=True;
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "HySLHIlckL9XFDg8THGh4JOJer73mUGG"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
