version: '3.9'

services:
  webapp:
    build: .
    ports:
      - "8070:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=3c0ad2a8-995b-4a41-b07a-1c223d485b91.hsvc.ir,32041;Database=MasjedSajad;User Id=sa;Password=STtk0HkTmkbZooXWZBelbeHvku2iZ94P;TrustServerCertificate=True;
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "STtk0HkTmkbZooXWZBelbeHvku2iZ94P"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
