version: '3.9'

services:
  webapp:
    build: .
    ports:
      - "8070:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=c901884d-10d0-4b98-b5d0-e0d930fd85ad.hsvc.ir,30802;Database=kbonyadala;User Id=sa;Password=3zVeYopmN2uUe6aqAyGoXKwZFEa1SjAD;TrustServerCertificate=True;
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "HySLHIlckL9XFDg8THGh4JOJer73mUGG"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
